name: CI workflow
on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build: 
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run : |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run : nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - name: Upload code coverage
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.xml
          flags: unittests
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          version: "v0.1.13"      